### ISSUE TITLE
Passing arguments into worker thread

### ISSUE THREAD

**Issue by LazyR0t** [eight04/pyWorker#4]
Thanks for publishing this package! :)
I want to be able to do something like:

    @create_worker
        worker(device: Device):
            device = device

    def main():
        device = device
        initialize(device)
        w = worker(device).start()

I don't want to initialize the device inside the thread and I think adding an event to initialize thread data would require additional checking within the thread loop. These are the only alternatives I could think of.

**Comment by eight04** [comment]
You can pass the arguments to `Worker.start`:
```python
from worker import Worker

def task(foo):
  print(foo)
  
Worker(task).start("my arg")
```
